security: setup gh attestation

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -44,25 +44,20 @@ jobs:
             echo "updated=false" >> $GITHUB_OUTPUT
           fi
 
-      - name: Verify GPG Signature
+      - name: Verify AppImage Artifact Attestation
         if: steps.update.outputs.updated == 'true'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          echo "importing Helium public GPG key"
-          gpg --import .github/workflows/helium-pubkey.asc
-
           VERSION="${{ steps.update.outputs.new_version }}"
           FILE="helium-${VERSION}-x86_64.AppImage"
 
-          echo "downloading AppImage and its signature file"
-          curl -sL "https://github.com/imputnet/helium-linux/releases/download/${VERSION}/${FILE}" -o "$FILE"
-          curl -sL "https://github.com/imputnet/helium-linux/releases/download/${VERSION}/${FILE}.asc" -o "${FILE}.asc"
+          curl -sLf "https://github.com/imputnet/helium-linux/releases/download/${VERSION}/${FILE}" -o "$FILE"
 
-          echo "Checking cryptographic signature..."
-          if ! gpg --verify "${FILE}.asc" "$FILE"; then
-            echo "ERROR: GPG signature verification failed!"
+          if ! gh attestation verify "$FILE" --repo "imputnet/helium-linux"; then
+            echo "ERROR: attestation failed"
             exit 1
           fi
-          echo "GPG signature verified successfully!"
 
       - name: Verify Build
         if: steps.update.outputs.updated == 'true'
